development:
  omniauth_client_id: <%= ENV["OMNIAUTH_CLIENT_ID"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: 7f122524476bea4938505afe13036419bb3c0c28ada7e5e18b7f55a8f0e7e353de534637affb6606d1b7b6e5e25d9de53db6d28b6236bd06ad918cbf86127a0f

test:
  secret_key_base: 966de98a37a0f0c2e2bb97df404126fc28310429ae19a0228a8c719cd0e4eb6348e9ee9e53340514e6a450aa6ac154b6a45f81595817eec872d92856859c1b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_client_id: <%= ENV["OMNIAUTH_CLIENT_ID"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
